# Generated by Django 4.1.6 on 2023-02-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busroute', '0002_rename_route_nmber_route_route_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_number',
            new_name='route_nmber',
        ),
    ]
